---
title: "Homework 6 (Optional)"
author: "[HX]{style='background-color: yellow;'}"
toc: true
title-block-banner: true
title-block-style: default
execute: 
  freeze: true
  cache: true
# format:
#html: # comment this line to get pdf
  pdf: 
    fig-width: 7
    fig-height: 7
---

[Link to the Github repository](https://github.com/psu-stat380/hw-6)

---

::: {.callout-important style="font-size: 0.8em;"}
## Due: Wed, May 3, 2023 @ 11:59pm

Please read the instructions carefully before submitting your assignment.

1. This assignment requires you to only upload a `PDF` file on Canvas
1. Don't collapse any code cells before submitting. 
1. Remember to make sure all your code output is rendered properly before uploading your submission.

⚠️ Please add your name to the author information in the frontmatter before submitting your assignment ⚠️
:::


In this assignment, we will perform various tasks involving principal component analysis (PCA), principal component regression, and dimensionality reduction.

We will need the following packages:


```{R, message=FALSE, warning=FALSE, results='hide'}
packages <- c(
  "tibble",
  "dplyr", 
  "readr", 
  "tidyr", 
  "purrr", 
  "broom",
  "magrittr",
  "corrplot",
  "car"
)
renv::install(packages)
sapply(packages, require, character.only=T)
```

<br><br><br><br>
---

## Question 1
::: {.callout-tip}
## 70 points
Principal component anlaysis and variable selection
:::

###### 1.1 (5 points)


The `data` folder contains a `spending.csv` dataset which is an illustrative sample of monthly spending data for a group of $5000$ people across a variety of categories. The response variable, `income`, is their monthly income, and objective is to predict the `income` for a an individual based on their spending patterns.

Read the data file as a tibble in R. Preprocess the data such that:

1. the variables are of the right data type, e.g., categorical variables are encoded as factors
2. all column names to lower case for consistency
3. Any observations with missing values are dropped

```{R}
path <- "data/spending.csv"

df <- read.csv(path)

colnames(df) <- tolower(colnames(df))

df <- na.omit(df)

sapply(df, class)
```

---

###### 1.2 (5 points)

Visualize the correlation between the variables using the `corrplot()` function. What do you observe? What does this mean for the model?

```{R}
df_x  <- df
corr_matrix <- cor(df_x)
corrplot(corr_matrix,method = "circle", type = "upper")
```

---

###### 1.3 (5 points)

Run a linear regression model to predict the `income` variable using the remaining predictors. Interpret the coefficients and summarize your results. 

The significant predictors are :
accessories, accommodation, audio_equipment, books, cameras, car_rentals, clothing, desktops, electronics, fast_food, groceries, gym_memberships, jewelry, laptops, magazines, meat, movies, music, outdoor_activities, restaurant_meals, shoes, smartphones, software, streaming_services, tablets, travel, vegetables, video_games, watches.


Among the significant predictors, only "vegetable" negatively correlates. Other predictors all have positive correlations with the dependent variable.

```{R}
model <- lm(income ~ ., data = df)
summary(model)
```

---

###### 1.3 (5 points)

Diagnose the model using the `vif()` function. What do you observe? What does this mean for the model?

I see that the model has high VIF values for all predictors, it suggests that there is multicollinearity. This can lead to inaccurate coefficient estimates, which can result in less reliable and less interpretable predictions. Re-evaluation is needed for building a reliable model.

```{R}
vif(model)
```

---

###### 1.4 (5 points)

Perform PCA using the `princomp` function in R. Print the summary of the PCA object.

40 principal components have been generated, which also correspond to the number of variables in the data.

The cumulative proportion of Comp.1 and Comp.2 explains over 94% of the total variance. This means that the first two principal components can accurately represent the data. 


```{R}
pca <- princomp(df)
summary(pca)
```

---

###### 1.5 (5 points)

Make a screeplot of the proportion of variance explained by each principal component. How many principal components would you choose to keep? Why?

I would keep two because they are the most significant.

```{R}
screeplot(pca, type="lines", main="Scree Plot")
```


###### 1.6 (5 points)

By setting any factor loadings below $0.2$ to $0$, summarize the factor loadings for the principal components that you chose to keep. 

```{R}
loadings <- pca$loadings[, 1:2]
loadings[abs(loadings) < 0.2] <- 0
summary(loadings)
```


Visualize the factor loadings. 

```{R}
biplot(pca, scale = 0, pc.biplot = TRUE, cex=0.8, col=c("blue", "red"))
```

---

###### 1.7 (15 points)

Based on the factor loadings, what do you think the principal components represent? 

Provide an interpreation for each principal component you chose to keep.

Based on the factor loadings, we can interpret the principal components as follows:

Principal Component 1: This component represents spending on accessories. These are items that people may spend money on but are not necessity.

Principal Component 2: This component represents spending on accomodation. This is living expenses.

Overall, the first two principal components capture different aspects of consumer spending patterns. These two components explain over 94% of the total variance in the data, indicating that they are the most important dimensions of variation in the spending patterns.

---

###### 1.8 (10 points)

Create a new data frame with the original response variable `income` and the principal components you chose to keep. Call this data frame `df_pca`.

```{R}
pcs <- predict(pca, newdata = df)[,1:2]
df_pca <- data.frame(income = df$income, pc1 = pcs[,1], pc2 = pcs[,2])
```

Fit a regression model to predict the `income` variable using the principal components you chose to keep. Interpret the coefficients and summarize your results. 

```{R}
model_pca <- lm(income ~ pc1 + pc2, data = df_pca)
summary(model_pca)
```

Compare the results of the regression model in 1.3 and 1.9. What do you observe? What does this mean for the model?

The regression model in 1.9, which used the two principal components as predictors, had a slightly lower R-suqred value(0.9995) than the model in 1.3(0.9999), which used all of the original predictors. This indicates that the two principal components explain most of the variation in the income than all of the original predictors combined.

Furthermore, from the anova, the regression model in 1.9 is vastly superior(P<0.001)

Overall, using principal component analysis to reduce the dimensionality of the predictors can improve the predictive performance of the model and enhance the interpretability of the coefficients.

```{R}
summary(model)
summary(model_pca)
anova(model,model_pca)
```

---

###### 1.10 (10 points)

Based on your interpretation of the principal components from Question 1.7, provide an interpretation of the regression model in Question 1.9.

The regression model in Question 1.9 used the two principal components that captured the most variability in the original dataset. 

The first principal component, which is a combination of variables with large positive loadings such as groceries, fast food, and restaurant meals, represents overall spending habits that are associated with a higher income. The second principal component, which is a combination of variables with positive loadings on outdoor activities, travel, and accommodation, represents spending habits that are associated with an active and adventurous lifestyle.

The regression model in Question 1.9 shows that the first principal component is positively associated with income, while the second principal component is negatively associated with income. Specifically, for every one-unit increase in the first principal component, we would expect to see a 90.07 increase in income. For every one-unit increase in the second principal component, we would expect to see a decrease of 0.0153 in income.

This means that individuals with higher scores on the first principal component (i.e., those who spend more on groceries, fast food, and restaurant meals) tend to have higher incomes, while individuals with higher scores on the second principal component (i.e., those who spend more on outdoor activities, travel, and accommodation) tend to have lower incomes. 

Overall, this regression model provides a simplified view of the relationship between spending habits and income, while accounting for the correlations between spending categories.

---


:::{.hidden unless-format="pdf"}
\pagebreak
:::

<br><br><br><br>
<br><br><br><br>
---



::: {.callout-note collapse="true"}
## Session Information

Print your `R` session information using the following command

```{R}
sessionInfo()
```
:::