<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="HX">

<title>Homework 6 (Optional)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Homework 6 (Optional)</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p><span style="background-color: yellow;">HX</span> </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p><a href="https://github.com/psu-stat380/hw-6">Link to the Github repository</a></p>
<hr>
<div class="callout callout-style-default callout-important callout-titled" style="font-size: 0.8em;">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Due: Wed, May 3, 2023 @ 11:59pm
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please read the instructions carefully before submitting your assignment.</p>
<ol type="1">
<li>This assignment requires you to only upload a <code>PDF</code> file on Canvas</li>
<li>Don’t collapse any code cells before submitting.</li>
<li>Remember to make sure all your code output is rendered properly before uploading your submission.</li>
</ol>
<p>⚠️ Please add your name to the author information in the frontmatter before submitting your assignment ⚠️</p>
</div>
</div>
<p>In this assignment, we will perform various tasks involving principal component analysis (PCA), principal component regression, and dimensionality reduction.</p>
<p>We will need the following packages:</p>
<div class="cell" data-hash="index_cache/html/unnamed-chunk-1_fc30cb4ec4bd0402d22b9a6ba3217ae8">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>packages <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tibble"</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"dplyr"</span>, </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"readr"</span>, </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tidyr"</span>, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"purrr"</span>, </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"broom"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"magrittr"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"corrplot"</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"car"</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>renv<span class="sc">::</span><span class="fu">install</span>(packages)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(packages, require, <span class="at">character.only=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br><br><br></p>
<hr>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
70 points
</div>
</div>
<div class="callout-body-container callout-body">
<p>Principal component anlaysis and variable selection</p>
</div>
</div>
<section id="points-1" class="level6">
<h6 class="anchored" data-anchor-id="points-1">1.1 (5 points)</h6>
<p>The <code>data</code> folder contains a <code>spending.csv</code> dataset which is an illustrative sample of monthly spending data for a group of <span class="math inline">\(5000\)</span> people across a variety of categories. The response variable, <code>income</code>, is their monthly income, and objective is to predict the <code>income</code> for a an individual based on their spending patterns.</p>
<p>Read the data file as a tibble in R. Preprocess the data such that:</p>
<ol type="1">
<li>the variables are of the right data type, e.g., categorical variables are encoded as factors</li>
<li>all column names to lower case for consistency</li>
<li>Any observations with missing values are dropped</li>
</ol>
<div class="cell" data-hash="index_cache/html/unnamed-chunk-2_390b70d360df4dde3a42d55398dd0bea">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>path <span class="ot">&lt;-</span> <span class="st">"data/spending.csv"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(path)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">colnames</span>(df))</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(df)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(df, class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          accessories         accommodation               alcohol 
            "numeric"             "numeric"             "numeric" 
      audio_equipment             beverages                 books 
            "numeric"             "numeric"             "numeric" 
              cameras           car_rentals              clothing 
            "numeric"             "numeric"             "numeric" 
         coffee_shops        dairy_products              desktops 
            "numeric"             "numeric"             "numeric" 
          electronics             fast_food         food_delivery 
            "numeric"             "numeric"             "numeric" 
               fruits             groceries       gym_memberships 
            "numeric"             "numeric"             "numeric" 
              jewelry               laptops             magazines 
            "numeric"             "numeric"             "numeric" 
                 meat                movies                 music 
            "numeric"             "numeric"             "numeric" 
   outdoor_activities public_transportation      restaurant_meals 
            "numeric"             "numeric"             "numeric" 
              seafood                 shoes           smartphones 
            "numeric"             "numeric"             "numeric" 
               snacks              software      sports_equipment 
            "numeric"             "numeric"             "numeric" 
   streaming_services               tablets                travel 
            "numeric"             "numeric"             "numeric" 
           vegetables           video_games               watches 
            "numeric"             "numeric"             "numeric" 
               income 
            "numeric" </code></pre>
</div>
</div>
<hr>
</section>
<section id="points-2" class="level6">
<h6 class="anchored" data-anchor-id="points-2">1.2 (5 points)</h6>
<p>Visualize the correlation between the variables using the <code>corrplot()</code> function. What do you observe? What does this mean for the model?</p>
<div class="cell" data-hash="index_cache/html/unnamed-chunk-3_e4a731b3eaadc3b1ff57b472b0fbdd99">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df_x  <span class="ot">&lt;-</span> df</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>corr_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(df_x)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(corr_matrix,<span class="at">method =</span> <span class="st">"circle"</span>, <span class="at">type =</span> <span class="st">"upper"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="points-3" class="level6">
<h6 class="anchored" data-anchor-id="points-3">1.3 (5 points)</h6>
<p>Run a linear regression model to predict the <code>income</code> variable using the remaining predictors. Interpret the coefficients and summarize your results.</p>
<p>The significant predictors are : accessories, accommodation, audio_equipment, books, cameras, car_rentals, clothing, desktops, electronics, fast_food, groceries, gym_memberships, jewelry, laptops, magazines, meat, movies, music, outdoor_activities, restaurant_meals, shoes, smartphones, software, streaming_services, tablets, travel, vegetables, video_games, watches.</p>
<p>Among the significant predictors, only “vegetable” negatively correlates. Other predictors all have positive correlations with the dependent variable.</p>
<div class="cell" data-hash="index_cache/html/unnamed-chunk-4_57e01fd0d443ccdf01e11dc4c8a34b86">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(income <span class="sc">~</span> ., <span class="at">data =</span> df)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ ., data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.6875 -1.6569  0.0427  1.6633  9.5623 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           -0.077509   0.121730  -0.637 0.524330    
accessories            0.299876   0.031786   9.434  &lt; 2e-16 ***
accommodation          0.113632   0.031262   3.635 0.000281 ***
alcohol               -0.005958   0.033266  -0.179 0.857873    
audio_equipment        0.602004   0.033483  17.979  &lt; 2e-16 ***
beverages              0.043335   0.034111   1.270 0.204000    
books                  0.070530   0.033238   2.122 0.033892 *  
cameras                0.461827   0.033572  13.756  &lt; 2e-16 ***
car_rentals            0.124875   0.032809   3.806 0.000143 ***
clothing               0.504228   0.026055  19.352  &lt; 2e-16 ***
coffee_shops           0.048839   0.034909   1.399 0.161864    
dairy_products         0.024548   0.032715   0.750 0.453082    
desktops               0.391673   0.033393  11.729  &lt; 2e-16 ***
electronics            1.079627   0.030035  35.946  &lt; 2e-16 ***
fast_food              0.077531   0.033014   2.348 0.018893 *  
food_delivery         -0.004903   0.034257  -0.143 0.886188    
fruits                 0.059089   0.033321   1.773 0.076237 .  
groceries              0.077694   0.031601   2.459 0.013981 *  
gym_memberships        0.141168   0.033410   4.225 2.43e-05 ***
jewelry                0.213726   0.032834   6.509 8.30e-11 ***
laptops                0.594328   0.032548  18.260  &lt; 2e-16 ***
magazines              0.080762   0.033694   2.397 0.016571 *  
meat                   0.081262   0.032367   2.511 0.012083 *  
movies                 0.110296   0.033326   3.310 0.000941 ***
music                  0.159925   0.033398   4.788 1.73e-06 ***
outdoor_activities     0.087846   0.032356   2.715 0.006651 ** 
public_transportation  0.061138   0.033022   1.851 0.064169 .  
restaurant_meals       0.066129   0.033225   1.990 0.046611 *  
seafood                0.061318   0.033786   1.815 0.069596 .  
shoes                  0.463185   0.029613  15.641  &lt; 2e-16 ***
smartphones            0.780150   0.031538  24.737  &lt; 2e-16 ***
snacks                 0.007464   0.033229   0.225 0.822290    
software               0.408500   0.034102  11.979  &lt; 2e-16 ***
sports_equipment       0.033328   0.033969   0.981 0.326574    
streaming_services     0.150614   0.031902   4.721 2.41e-06 ***
tablets                0.637266   0.033133  19.234  &lt; 2e-16 ***
travel                 0.129161   0.031457   4.106 4.09e-05 ***
vegetables            -0.066111   0.033162  -1.994 0.046257 *  
video_games            0.863309   0.031392  27.501  &lt; 2e-16 ***
watches                0.145853   0.033467   4.358 1.34e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.434 on 4960 degrees of freedom
Multiple R-squared:  0.9999,    Adjusted R-squared:  0.9999 
F-statistic: 1.834e+06 on 39 and 4960 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<hr>
</section>
<section id="points-4" class="level6">
<h6 class="anchored" data-anchor-id="points-4">1.3 (5 points)</h6>
<p>Diagnose the model using the <code>vif()</code> function. What do you observe? What does this mean for the model?</p>
<p>I see that the model has high VIF values for all predictors, it suggests that there is multicollinearity. This can lead to inaccurate coefficient estimates, which can result in less reliable and less interpretable predictions. Re-evaluation is needed for building a reliable model.</p>
<div class="cell" data-hash="index_cache/html/unnamed-chunk-5_1ceaf47b468bbf7d620adf8f0b4a4b83">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          accessories         accommodation               alcohol 
            152.06821             681.15504             387.23376 
      audio_equipment             beverages                 books 
           1755.56441             914.69186             192.91781 
              cameras           car_rentals              clothing 
            785.43147             423.55906             282.25143 
         coffee_shops        dairy_products              desktops 
            425.39644            2336.74847             776.75697 
          electronics             fast_food         food_delivery 
           3927.16511            1519.85171             921.68162 
               fruits             groceries       gym_memberships 
           1550.05678            3136.80325             438.30224 
              jewelry               laptops             magazines 
             72.38215            1658.76990             198.53619 
                 meat                movies                 music 
           2284.43676             437.28082             437.03990 
   outdoor_activities public_transportation      restaurant_meals 
            411.17302             427.77815            1540.26240 
              seafood                 shoes           smartphones 
           1594.08027             233.33301            2772.27822 
               snacks              software      sports_equipment 
            868.24282             810.28919             201.00255 
   streaming_services               tablets                travel 
            709.25592            1718.78339             690.69616 
           vegetables           video_games               watches 
           1536.40686            2745.64421              75.56457 </code></pre>
</div>
</div>
<hr>
</section>
<section id="points-5" class="level6">
<h6 class="anchored" data-anchor-id="points-5">1.4 (5 points)</h6>
<p>Perform PCA using the <code>princomp</code> function in R. Print the summary of the PCA object.</p>
<p>40 principal components have been generated, which also correspond to the number of variables in the data.</p>
<p>The cumulative proportion of Comp.1 and Comp.2 explains over 94% of the total variance. This means that the first two principal components can accurately represent the data.</p>
<div class="cell" data-hash="index_cache/html/unnamed-chunk-6_c91085d723b0fc9e2f0b6329ebef046b">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>pca <span class="ot">&lt;-</span> <span class="fu">princomp</span>(df)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                            Comp.1      Comp.2      Comp.3       Comp.4
Standard deviation     323.0278864 143.7393654 77.51287691 35.533628867
Proportion of Variance   0.7886259   0.1561502  0.04540867  0.009542675
Cumulative Proportion    0.7886259   0.9447761  0.99018477  0.999727448
                             Comp.5       Comp.6       Comp.7       Comp.8
Standard deviation     1.087955e+00 1.071244e+00 1.066408e+00 1.056882e+00
Proportion of Variance 8.945666e-06 8.672968e-06 8.594835e-06 8.441971e-06
Cumulative Proportion  9.997364e-01 9.997451e-01 9.997537e-01 9.997621e-01
                             Comp.9      Comp.10      Comp.11      Comp.12
Standard deviation     1.054090e+00 1.051061e+00 1.045351e+00 1.042679e+00
Proportion of Variance 8.397426e-06 8.349240e-06 8.258768e-06 8.216599e-06
Cumulative Proportion  9.997705e-01 9.997789e-01 9.997871e-01 9.997953e-01
                            Comp.13      Comp.14      Comp.15      Comp.16
Standard deviation     1.037965e+00 1.036462e+00 1.027953e+00 1.022946e+00
Proportion of Variance 8.142472e-06 8.118917e-06 7.986155e-06 7.908548e-06
Cumulative Proportion  9.998035e-01 9.998116e-01 9.998196e-01 9.998275e-01
                            Comp.17      Comp.18      Comp.19      Comp.20
Standard deviation     1.020268e+00 1.015862e+00 1.014161e+00 1.009587e+00
Proportion of Variance 7.867188e-06 7.799389e-06 7.773291e-06 7.703329e-06
Cumulative Proportion  9.998353e-01 9.998431e-01 9.998509e-01 9.998586e-01
                            Comp.21      Comp.22      Comp.23      Comp.24
Standard deviation     1.008328e+00 1.005136e+00 9.996464e-01 9.917451e-01
Proportion of Variance 7.684134e-06 7.635553e-06 7.552380e-06 7.433463e-06
Cumulative Proportion  9.998663e-01 9.998739e-01 9.998815e-01 9.998889e-01
                            Comp.25      Comp.26      Comp.27      Comp.28
Standard deviation     9.909781e-01 9.897431e-01 9.810386e-01 9.737408e-01
Proportion of Variance 7.421969e-06 7.403481e-06 7.273830e-06 7.166016e-06
Cumulative Proportion  9.998964e-01 9.999038e-01 9.999110e-01 9.999182e-01
                            Comp.29      Comp.30      Comp.31      Comp.32
Standard deviation     9.709381e-01 9.689219e-01 9.682985e-01 9.616863e-01
Proportion of Variance 7.124824e-06 7.095265e-06 7.086138e-06 6.989689e-06
Cumulative Proportion  9.999253e-01 9.999324e-01 9.999395e-01 9.999465e-01
                            Comp.33      Comp.34      Comp.35      Comp.36
Standard deviation     9.600143e-01 9.545376e-01 9.509890e-01 9.463352e-01
Proportion of Variance 6.965406e-06 6.886160e-06 6.835055e-06 6.768322e-06
Cumulative Proportion  9.999535e-01 9.999603e-01 9.999672e-01 9.999739e-01
                            Comp.37      Comp.38      Comp.39      Comp.40
Standard deviation     9.382236e-01 9.303035e-01 9.250413e-01 9.197035e-01
Proportion of Variance 6.652788e-06 6.540943e-06 6.467154e-06 6.392735e-06
Cumulative Proportion  9.999806e-01 9.999871e-01 9.999936e-01 1.000000e+00</code></pre>
</div>
</div>
<hr>
</section>
<section id="points-6" class="level6">
<h6 class="anchored" data-anchor-id="points-6">1.5 (5 points)</h6>
<p>Make a screeplot of the proportion of variance explained by each principal component. How many principal components would you choose to keep? Why?</p>
<p>I would keep two because they are the most significant.</p>
<div class="cell" data-hash="index_cache/html/unnamed-chunk-7_7dcd130e3eeb1339e8a7d59743cf265f">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">screeplot</span>(pca, <span class="at">type=</span><span class="st">"lines"</span>, <span class="at">main=</span><span class="st">"Scree Plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="points-7" class="level6">
<h6 class="anchored" data-anchor-id="points-7">1.6 (5 points)</h6>
<p>By setting any factor loadings below <span class="math inline">\(0.2\)</span> to <span class="math inline">\(0\)</span>, summarize the factor loadings for the principal components that you chose to keep.</p>
<div class="cell" data-hash="index_cache/html/unnamed-chunk-8_ca69bb12f05c113a5944499c5c31a603">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="ot">&lt;-</span> pca<span class="sc">$</span>loadings[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>loadings[<span class="fu">abs</span>(loadings) <span class="sc">&lt;</span> <span class="fl">0.2</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(loadings)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Comp.1            Comp.2        
 Min.   :0.00000   Min.   :-0.42178  
 1st Qu.:0.00000   1st Qu.:-0.21085  
 Median :0.00000   Median : 0.00000  
 Mean   :0.02802   Mean   :-0.07908  
 3rd Qu.:0.00000   3rd Qu.: 0.00000  
 Max.   :0.90075   Max.   : 0.00000  </code></pre>
</div>
</div>
<p>Visualize the factor loadings.</p>
<div class="cell" data-hash="index_cache/html/unnamed-chunk-9_8dec135c8116b68bf8580a5e559acd1c">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">biplot</span>(pca, <span class="at">scale =</span> <span class="dv">0</span>, <span class="at">pc.biplot =</span> <span class="cn">TRUE</span>, <span class="at">cex=</span><span class="fl">0.8</span>, <span class="at">col=</span><span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="points-8" class="level6">
<h6 class="anchored" data-anchor-id="points-8">1.7 (15 points)</h6>
<p>Based on the factor loadings, what do you think the principal components represent?</p>
<p>Provide an interpreation for each principal component you chose to keep.</p>
<p>Based on the factor loadings, we can interpret the principal components as follows:</p>
<p>Principal Component 1: This component represents spending on accessories. These are items that people may spend money on but are not necessity.</p>
<p>Principal Component 2: This component represents spending on accomodation. This is living expenses.</p>
<p>Overall, the first two principal components capture different aspects of consumer spending patterns. These two components explain over 94% of the total variance in the data, indicating that they are the most important dimensions of variation in the spending patterns.</p>
<hr>
</section>
<section id="points-9" class="level6">
<h6 class="anchored" data-anchor-id="points-9">1.8 (10 points)</h6>
<p>Create a new data frame with the original response variable <code>income</code> and the principal components you chose to keep. Call this data frame <code>df_pca</code>.</p>
<div class="cell" data-hash="index_cache/html/unnamed-chunk-10_2935883ed2fda49949e34d5337d91978">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>pcs <span class="ot">&lt;-</span> <span class="fu">predict</span>(pca, <span class="at">newdata =</span> df)[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>df_pca <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">income =</span> df<span class="sc">$</span>income, <span class="at">pc1 =</span> pcs[,<span class="dv">1</span>], <span class="at">pc2 =</span> pcs[,<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Fit a regression model to predict the <code>income</code> variable using the principal components you chose to keep. Interpret the coefficients and summarize your results.</p>
<div class="cell" data-hash="index_cache/html/unnamed-chunk-11_6d009f1906105637dcc2afca075535c1">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>model_pca <span class="ot">&lt;-</span> <span class="fu">lm</span>(income <span class="sc">~</span> pc1 <span class="sc">+</span> pc2, <span class="at">data =</span> df_pca)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_pca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ pc1 + pc2, data = df_pca)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.3810  -4.7364   0.0639   4.7209  16.7311 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 6.282e+02  9.116e-02 6890.69   &lt;2e-16 ***
pc1         9.007e-01  2.822e-04 3191.70   &lt;2e-16 ***
pc2         1.536e-02  6.342e-04   24.22   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.446 on 4997 degrees of freedom
Multiple R-squared:  0.9995,    Adjusted R-squared:  0.9995 
F-statistic: 5.094e+06 on 2 and 4997 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Compare the results of the regression model in 1.3 and 1.9. What do you observe? What does this mean for the model?</p>
<p>The regression model in 1.9, which used the two principal components as predictors, had a slightly lower R-suqred value(0.9995) than the model in 1.3(0.9999), which used all of the original predictors. This indicates that the two principal components explain most of the variation in the income than all of the original predictors combined.</p>
<p>Furthermore, from the anova, the regression model in 1.9 is vastly superior(P&lt;0.001)</p>
<p>Overall, using principal component analysis to reduce the dimensionality of the predictors can improve the predictive performance of the model and enhance the interpretability of the coefficients.</p>
<div class="cell" data-hash="index_cache/html/unnamed-chunk-12_f3890b0e2029efcca9b626f28235f4e0">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ ., data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.6875 -1.6569  0.0427  1.6633  9.5623 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           -0.077509   0.121730  -0.637 0.524330    
accessories            0.299876   0.031786   9.434  &lt; 2e-16 ***
accommodation          0.113632   0.031262   3.635 0.000281 ***
alcohol               -0.005958   0.033266  -0.179 0.857873    
audio_equipment        0.602004   0.033483  17.979  &lt; 2e-16 ***
beverages              0.043335   0.034111   1.270 0.204000    
books                  0.070530   0.033238   2.122 0.033892 *  
cameras                0.461827   0.033572  13.756  &lt; 2e-16 ***
car_rentals            0.124875   0.032809   3.806 0.000143 ***
clothing               0.504228   0.026055  19.352  &lt; 2e-16 ***
coffee_shops           0.048839   0.034909   1.399 0.161864    
dairy_products         0.024548   0.032715   0.750 0.453082    
desktops               0.391673   0.033393  11.729  &lt; 2e-16 ***
electronics            1.079627   0.030035  35.946  &lt; 2e-16 ***
fast_food              0.077531   0.033014   2.348 0.018893 *  
food_delivery         -0.004903   0.034257  -0.143 0.886188    
fruits                 0.059089   0.033321   1.773 0.076237 .  
groceries              0.077694   0.031601   2.459 0.013981 *  
gym_memberships        0.141168   0.033410   4.225 2.43e-05 ***
jewelry                0.213726   0.032834   6.509 8.30e-11 ***
laptops                0.594328   0.032548  18.260  &lt; 2e-16 ***
magazines              0.080762   0.033694   2.397 0.016571 *  
meat                   0.081262   0.032367   2.511 0.012083 *  
movies                 0.110296   0.033326   3.310 0.000941 ***
music                  0.159925   0.033398   4.788 1.73e-06 ***
outdoor_activities     0.087846   0.032356   2.715 0.006651 ** 
public_transportation  0.061138   0.033022   1.851 0.064169 .  
restaurant_meals       0.066129   0.033225   1.990 0.046611 *  
seafood                0.061318   0.033786   1.815 0.069596 .  
shoes                  0.463185   0.029613  15.641  &lt; 2e-16 ***
smartphones            0.780150   0.031538  24.737  &lt; 2e-16 ***
snacks                 0.007464   0.033229   0.225 0.822290    
software               0.408500   0.034102  11.979  &lt; 2e-16 ***
sports_equipment       0.033328   0.033969   0.981 0.326574    
streaming_services     0.150614   0.031902   4.721 2.41e-06 ***
tablets                0.637266   0.033133  19.234  &lt; 2e-16 ***
travel                 0.129161   0.031457   4.106 4.09e-05 ***
vegetables            -0.066111   0.033162  -1.994 0.046257 *  
video_games            0.863309   0.031392  27.501  &lt; 2e-16 ***
watches                0.145853   0.033467   4.358 1.34e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.434 on 4960 degrees of freedom
Multiple R-squared:  0.9999,    Adjusted R-squared:  0.9999 
F-statistic: 1.834e+06 on 39 and 4960 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_pca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ pc1 + pc2, data = df_pca)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.3810  -4.7364   0.0639   4.7209  16.7311 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 6.282e+02  9.116e-02 6890.69   &lt;2e-16 ***
pc1         9.007e-01  2.822e-04 3191.70   &lt;2e-16 ***
pc2         1.536e-02  6.342e-04   24.22   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.446 on 4997 degrees of freedom
Multiple R-squared:  0.9995,    Adjusted R-squared:  0.9995 
F-statistic: 5.094e+06 on 2 and 4997 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model,model_pca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: income ~ accessories + accommodation + alcohol + audio_equipment + 
    beverages + books + cameras + car_rentals + clothing + coffee_shops + 
    dairy_products + desktops + electronics + fast_food + food_delivery + 
    fruits + groceries + gym_memberships + jewelry + laptops + 
    magazines + meat + movies + music + outdoor_activities + 
    public_transportation + restaurant_meals + seafood + shoes + 
    smartphones + snacks + software + sports_equipment + streaming_services + 
    tablets + travel + vegetables + video_games + watches
Model 2: income ~ pc1 + pc2
  Res.Df    RSS  Df Sum of Sq      F    Pr(&gt;F)    
1   4960  29374                                   
2   4997 207644 -37   -178270 813.58 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<hr>
</section>
<section id="points-10" class="level6">
<h6 class="anchored" data-anchor-id="points-10">1.10 (10 points)</h6>
<p>Based on your interpretation of the principal components from Question 1.7, provide an interpretation of the regression model in Question 1.9.</p>
<p>The regression model in Question 1.9 used the two principal components that captured the most variability in the original dataset.</p>
<p>The first principal component, which is a combination of variables with large positive loadings such as groceries, fast food, and restaurant meals, represents overall spending habits that are associated with a higher income. The second principal component, which is a combination of variables with positive loadings on outdoor activities, travel, and accommodation, represents spending habits that are associated with an active and adventurous lifestyle.</p>
<p>The regression model in Question 1.9 shows that the first principal component is positively associated with income, while the second principal component is negatively associated with income. Specifically, for every one-unit increase in the first principal component, we would expect to see a 90.07 increase in income. For every one-unit increase in the second principal component, we would expect to see a decrease of 0.0153 in income.</p>
<p>This means that individuals with higher scores on the first principal component (i.e., those who spend more on groceries, fast food, and restaurant meals) tend to have higher incomes, while individuals with higher scores on the second principal component (i.e., those who spend more on outdoor activities, travel, and accommodation) tend to have lower incomes.</p>
<p>Overall, this regression model provides a simplified view of the relationship between spending habits and income, while accounting for the correlations between spending categories.</p>
<hr>
<div class="hidden" data-unless-format="pdf">
<div style="page-break-after: always;"></div>
</div>
<p><br><br><br><br> <br><br><br><br></p>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Session Information
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Print your <code>R</code> session information using the following command</p>
<div class="cell" data-hash="index_cache/html/unnamed-chunk-13_88bd08c5e37ab9d7935f874f6fdf50e6">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.3.0 (2023-04-21)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.2.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
 [1] car_3.1-2        carData_3.0-5    tibble_3.2.1     luz_0.4.0       
 [5] torch_0.10.0     e1071_1.7-13     rpart.plot_3.1.1 rpart_4.1.19    
 [9] caret_6.0-94     lattice_0.21-8   ggplot2_3.4.2    corrplot_0.92   
[13] magrittr_2.0.3   broom_1.0.4      purrr_1.0.1      tidyr_1.3.0     
[17] readr_2.1.4      dplyr_1.1.2     

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.0     timeDate_4022.108    fastmap_1.1.1       
 [4] pROC_1.18.0          digest_0.6.31        timechange_0.2.0    
 [7] lifecycle_1.0.3      processx_3.8.1       survival_3.5-5      
[10] compiler_4.3.0       progress_1.2.2       rlang_1.1.1         
[13] tools_4.3.0          utf8_1.2.3           yaml_2.3.7          
[16] data.table_1.14.8    knitr_1.42           prettyunits_1.1.1   
[19] bit_4.0.5            plyr_1.8.8           abind_1.4-5         
[22] withr_2.5.0          nnet_7.3-18          grid_4.3.0          
[25] stats4_4.3.0         fansi_1.0.4          colorspace_2.1-0    
[28] future_1.32.0        globals_0.16.2       scales_1.2.1        
[31] iterators_1.0.14     MASS_7.3-59          zeallot_0.1.0       
[34] cli_3.6.1            crayon_1.5.2         rmarkdown_2.21      
[37] generics_0.1.3       future.apply_1.10.0  reshape2_1.4.4      
[40] tzdb_0.3.0           proxy_0.4-27         stringr_1.5.0       
[43] splines_4.3.0        parallel_4.3.0       coro_1.0.3          
[46] vctrs_0.6.2          hardhat_1.3.0        Matrix_1.5-4        
[49] jsonlite_1.8.4       callr_3.7.3          hms_1.1.3           
[52] bit64_4.0.5          listenv_0.9.0        foreach_1.5.2       
[55] gower_1.0.1          recipes_1.0.6        glue_1.6.2          
[58] parallelly_1.35.0    ps_1.7.5             codetools_0.2-19    
[61] lubridate_1.9.2      stringi_1.7.12       gtable_0.3.3        
[64] munsell_0.5.0        pillar_1.9.0         htmltools_0.5.5     
[67] ipred_0.9-14         lava_1.7.2.1         R6_2.5.1            
[70] evaluate_0.20        backports_1.4.1      renv_0.16.0-53      
[73] class_7.3-21         Rcpp_1.0.10          nlme_3.1-162        
[76] prodlim_2023.03.31   xfun_0.39            fs_1.6.2            
[79] pkgconfig_2.0.3      ModelMetrics_1.2.2.2</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>